# Generated by Django 5.1.1 on 2024-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Utilizator", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="adresa de e-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_ngohub_user",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="We do not use this field",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="nume utilizator",
            ),
        ),
    ]
