# Generated by Django 3.1.2 on 2020-10-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugin_woocommerce', '0002_auto_20201006_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskresult',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='taskresult',
            old_name='errors',
            new_name='stats',
        ),
        migrations.RemoveField(
            model_name='taskresult',
            name='updates',
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woocommerce_tasks_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(choices=[('sync', 'Import tables')], max_length=100)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('last_edit_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woocommerce_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='plugin_woocommerce.task'),
        ),
    ]
