name: paul_prod

services:

  db:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql
    container_name: paul_db

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend_base
    container_name: paul_backend
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
    environment:
      DATABASE_HOST: "paul_db"
    volumes:
      - ./backend/media:/var/www/paul/backend/media
    depends_on:
      - db
    ports:
      - "${WEBAPP_PORT:-8080}:80"

volumes:
  paul_psql:
