name: paul_dev

services:

  db:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend_base
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.dev
    volumes:
      - ./backend:/var/www/paul/backend
    depends_on:
      - db
    ports:
      - "5678:5678"
      - "5677:5677"
      - "${WEBAPP_PORT:-8080}:8000"

volumes:
  paul_psql:
