# Generated by Django 3.1 on 2020-08-27 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_tablecolumn_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CsvFieldMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=100)),
                ("field_name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("int", "int"),
                            ("float", "float"),
                            ("text", "text"),
                            ("date", "date"),
                            ("bool", "bool"),
                            ("object", "object"),
                            ("enum", "enum"),
                        ],
                        default=("int", "int"),
                        max_length=20,
                    ),
                ),
                ("field_format", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="table",
            name="csv_field_mapping",
        ),
        migrations.DeleteModel(
            name="CsvFiledMap",
        ),
        migrations.AddField(
            model_name="csvfieldmap",
            name="table",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="csv_field_map",
                to="api.table",
            ),
        ),
    ]
