# Generated by Django 3.1.1 on 2020-09-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20200907_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvimport",
            name="delimiter",
            field=models.CharField(blank=True, default=";", max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="csvimport",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="csv_imports",
                to="api.table",
            ),
        ),
    ]
