# Generated by Django 3.1.1 on 2020-09-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20200908_2140"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filter",
            name="join_field",
        ),
        migrations.RemoveField(
            model_name="filter",
            name="primary_table",
        ),
        migrations.RemoveField(
            model_name="filter",
            name="primary_table_fields",
        ),
    ]
