# Generated by Django 3.1.1 on 2020-09-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_auto_20200908_2148"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filter",
            name="join_tables",
        ),
        migrations.RemoveField(
            model_name="filterjointable",
            name="filter",
        ),
        migrations.AddField(
            model_name="filter",
            name="primary_table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.filterjointable",
            ),
        ),
    ]
