# Generated by Django 3.1.1 on 2020-09-22 09:06

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0024_auto_20200909_1416"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("timeline_period", models.CharField(blank=True, max_length=20, null=True)),
                ("timeline_include_nulls", models.BooleanField(default=False)),
                (
                    "y_axis_function",
                    models.CharField(
                        choices=[
                            ("Count", "Count"),
                            ("Sum", "Sum"),
                            ("Min", "Min"),
                            ("Max", "Max"),
                            ("Avg", "Average"),
                        ],
                        default="Count",
                        max_length=10,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_edit_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_edit_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_chart_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("table", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.table")),
                (
                    "timeline_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charts_timeline_fields",
                        to="api.tablecolumn",
                    ),
                ),
                (
                    "x_axis_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charts_x_axis_fields",
                        to="api.tablecolumn",
                    ),
                ),
                (
                    "y_axis_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charts_y_axis_fields",
                        to="api.tablecolumn",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_charts",
            field=models.ManyToManyField(blank=True, null=True, to="api.Chart"),
        ),
    ]
