# Generated by Django 3.1.1 on 2020-09-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_chart_chart_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'ordering': ['table']},
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('Line', 'Line'), ('Bar', 'Bar'), ('Pie', 'Pie'), ('Doughnut', 'Doughnut')], default='Line', max_length=20),
        ),
        migrations.AlterField(
            model_name='chart',
            name='timeline_period',
            field=models.CharField(blank=True, choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='minute', max_length=20, null=True),
        ),
    ]
