# Generated by Django 3.1.1 on 2020-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_chart_x_axis_field_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='y_axis_function',
            field=models.CharField(choices=[('Count', 'Count'), ('Sum', 'Sum'), ('Min', 'Min'), ('Max', 'Max'), ('Avg', 'Average'), ('StdDev', 'Standard Deviation')], default='Count', max_length=10),
        ),
    ]
