# Generated by Django 3.1.2 on 2020-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200929_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_charts',
            field=models.ManyToManyField(blank=True, to='api.Chart'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_filters',
            field=models.ManyToManyField(blank=True, to='api.Filter'),
        ),
    ]
