# Generated by Django 3.1.2 on 2020-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20201009_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='default_fields',
            field=models.ManyToManyField(null=True, related_name='default_field', to='api.TableColumn'),
        ),
    ]
