# Generated by Django 3.1.2 on 2020-10-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_table_default_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='default_fields',
            field=models.ManyToManyField(related_name='filter_default_field', to='api.TableColumn'),
        ),
    ]
