# Generated by Django 3.1.2 on 2020-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_filter_default_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='default_fields',
            field=models.ManyToManyField(null=True, related_name='filter_default_field', to='api.TableColumn'),
        ),
    ]
