# Generated by Django 3.1.2 on 2020-10-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20201015_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterjointable',
            name='join_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tablecolumn'),
        ),
    ]
