# Generated by Django 3.1.4 on 2021-01-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201029_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dashboard_cards',
        ),
        migrations.CreateModel(
            name='UserCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, help_text='What order to display this card within the profile dashboard.', max_length=255, verbose_name='Order')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.card')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Profile Card',
                'verbose_name_plural': 'Profile cards',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cards',
            field=models.ManyToManyField(blank=True, through='api.UserCards', to='api.Card'),
        ),
    ]
