# Generated by Django 3.1.4 on 2021-01-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210118_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCards',
            new_name='UserCard',
        ),
    ]
