# Generated by Django 3.2.9 on 2021-12-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20211206_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvimport',
            old_name='imports_count',
            new_name='import_count_created',
        ),
        migrations.AddField(
            model_name='csvimport',
            name='import_count_updated',
            field=models.IntegerField(default=0),
        ),
    ]
