# Generated by Django 3.2.14 on 2022-09-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20220730_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='import_count_skipped',
            field=models.IntegerField(default=0),
        ),
    ]
