# Generated by Django 3.1.2 on 2020-10-06 06:41

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


def init_settings(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Settings = apps.get_model("plugin_mailchimp", "Settings")
    Settings.objects.create(
        key='key',
        audience_list_name="[mailchimp] Audiences",
        audiences_members_list_name="[mailchimp] Audiences members"
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('audience_list_name', models.CharField(max_length=255)),
                ('audiences_members_list_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('errors', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('updates', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailchimp_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(init_settings),
    ]
