# Generated by Django 3.1.2 on 2020-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='audiences_stats_table_name',
            field=models.CharField(default='[mailchimp] Audiences stats', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='audience_list_name',
            field=models.CharField(default='[mailchimp] Audiences', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='audiences_members_list_name',
            field=models.CharField(default='[mailchimp] Audiences members', max_length=255),
        ),
    ]
