# Generated by Django 3.1.2 on 2020-10-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0003_auto_20201006_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='audience_segments_table_name',
            field=models.CharField(default='[mailchimp] Audience Segments', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='audiences_members_table_name',
            field=models.CharField(default='[mailchimp] Audiences Members', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='audiences_stats_table_name',
            field=models.CharField(default='[mailchimp] Audiences Stats', max_length=255),
        ),
    ]
