# Generated by Django 3.1.2 on 2020-10-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0006_auto_20201006_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='audience_segment_members_table_name',
            field=models.CharField(default='[mailchimp] Segments Members', max_length=255),
        ),
    ]
