# Generated by Django 3.1.2 on 2020-10-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0007_settings_audience_segment_members_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='audience_segment_members_table_name',
            new_name='segment_members_table_name',
        ),
    ]
