# Generated by Django 3.1.2 on 2020-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0009_auto_20201007_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskresult',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='settings',
            name='audience_tags_table_name',
            field=models.CharField(default='[mailchimp] Audience Tags', max_length=255),
        ),
    ]
