# Generated by Django 3.1.2 on 2020-10-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0012_auto_20201007_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationtask',
            name='audience_id',
        ),
        migrations.RemoveField(
            model_name='segmentationtask',
            name='email_field',
        ),
    ]
