# Generated by Django 3.1.2 on 2020-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0013_auto_20201008_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Finished', max_length=20),
        ),
    ]
