# Generated by Django 3.1.2 on 2020-11-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugin_mailchimp', '0018_auto_20201102_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_mailchimp_taskresult_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
