# Generated by Django 3.1.2 on 2020-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0019_auto_20201102_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
