# Generated by Django 3.2.18 on 2023-04-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0017_task_cluster_alter'),
        ('plugin_mailchimp', '0025_auto_20230414_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'get_latest_by': 'created_on', 'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        # migrations.RemoveField(
        #     model_name='task',
        #     name='periodic_task',
        # ),
        migrations.AddField(
            model_name='task',
            name='periodic_task_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailchimp_tasks', to='django_q.schedule'),
        ),
    ]
