# Generated by Django 3.2.18 on 2023-04-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0026_auto_20230418_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='periodic_task_enabled',
            new_name='schedule_enabled',
        ),
    ]
