# Generated by Django 3.2.18 on 2023-04-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0028_auto_20230419_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('sync', 'Import data from Mailchimp'), ('segmentation', 'Send segmentation to Mailchimp'), ('upload', 'Send contacts to Mailchimp (WIP/TODO)')], db_index=True, max_length=12),
        ),
    ]
