# Generated by Django 3.2.18 on 2023-05-05 06:45

from django.db import migrations

from plugin_mailchimp.utils import update_entry_data_keys
from plugin_mailchimp.table_fields import TABLE_MAPPING


def rename_data_keys(apps, schema_editor):
    Table = apps.get_model("api", "Table")
    Entry = apps.get_model("api", "Entry")

    audience_members_table_fields_defs = TABLE_MAPPING['audience_members']
    contact_table_fields_defs = TABLE_MAPPING['contact_merge_fields']

    try:
        table = Table.objects.filter(table_type="C")[0]
    except IndexError:
        # No Contacts table exists
        return

    update_entry_data_keys(
        table, 
        Entry, 
        audience_members_table_fields_defs | contact_table_fields_defs
    )


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0033_rename_contacts_columns'),
    ]

    operations = [
        migrations.RunPython(rename_data_keys)
    ]
