# Generated by Django 3.1 on 2020-08-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200827_0422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvimport",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
