# Generated by Django 3.1 on 2020-08-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200827_0429"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvimport",
            name="field_mapping",
        ),
        migrations.AddField(
            model_name="table",
            name="csv_field_mapping",
            field=models.ManyToManyField(to="api.CsvFiledMap"),
        ),
    ]
