# Generated by Django 3.1 on 2020-08-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_csvimport_errors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csvimport",
            old_name="imported_count",
            new_name="imports_count",
        ),
    ]
