# Generated by Django 3.1.1 on 2020-09-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20200907_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfieldmap",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="csv_field_mapping",
                to="api.csvimport",
            ),
        ),
        migrations.AlterField(
            model_name="csvfieldmap",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="csv_field_mapping",
                to="api.table",
            ),
        ),
    ]
