# Generated by Django 3.1.1 on 2020-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auto_20200907_1829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
