# Generated by Django 3.1.1 on 2020-09-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_auto_20200908_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="join_tables",
            field=models.ManyToManyField(related_name="filter_join_table", to="api.FilterJoinTable"),
        ),
    ]
