# Generated by Django 3.1.1 on 2020-09-09 11:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_filter_join_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="filters",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="filters",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
