# Generated by Django 3.1.1 on 2020-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20200922_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="chart_type",
            field=models.CharField(default="Line", max_length=20),
        ),
    ]
