# Generated by Django 3.1.2 on 2020-10-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201019_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfieldmap',
            name='table_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tablecolumn'),
        ),
        migrations.AlterField(
            model_name='csvfieldmap',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csvfieldmap',
            name='field_type',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('text', 'text'), ('date', 'date'), ('bool', 'bool'), ('object', 'object'), ('enum', 'enum')], default=('int', 'int'), max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='default_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='filter_default_field', to='api.TableColumn'),
        ),
        migrations.AlterField(
            model_name='table',
            name='default_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='default_field', to='api.TableColumn'),
        ),
    ]
