# Generated by Django 3.1.2 on 2020-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20201020_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfieldmap',
            old_name='field_name',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='csvfieldmap',
            name='field_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('bool', 'bool'), ('object', 'object'), ('enum', 'enum')], default='text', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('bool', 'bool'), ('object', 'object'), ('enum', 'enum')], max_length=20),
        ),
    ]
