# Generated by Django 3.1.2 on 2020-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userprofile_dashboard_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='default_fields',
            field=models.ManyToManyField(blank=True, related_name='filter_default_field', to='api.TableColumn'),
        ),
        migrations.AlterField(
            model_name='table',
            name='default_fields',
            field=models.ManyToManyField(blank=True, related_name='default_field', to='api.TableColumn'),
        ),
    ]
