# Generated by Django 3.1.4 on 2021-01-19 15:59

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Table = apps.get_model("api", "Table")
    for table in Table.objects.all():
        date_fields = []
        print('---', table)

        for field in table.fields.filter(field_type="date"):
            print(field.name)
            date_fields.append(field.name)
        i = 0
        for entry in table.entries.all():
            i += 1
            print(i, table)
            for field in date_fields:
                try:
                    entry.data[field] = entry.data[field][:10]
                except:
                    print('****errr:', entry.data)
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210118_1052'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
