# Generated by Django 3.1.5 on 2021-01-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210119_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfieldmap',
            name='field_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('enum', 'enum')], default='text', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('int', 'int'), ('float', 'float'), ('date', 'date'), ('enum', 'enum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='api.userprofile'),
        ),
    ]
