# Generated by Django 3.2.14 on 2022-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_csvimport_import_count_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Preferred language', max_length=10),
        ),
    ]
