# Generated by Django 3.2.18 on 2023-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20221118_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(blank=True, choices=[('', 'regular'), ('C', 'contacts')], default='', max_length=1, verbose_name='type'),
        ),
    ]
