# Generated by Django 3.2.18 on 2023-04-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_table_table_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': (('update_content', 'Can update table content'),), 'verbose_name': 'table', 'verbose_name_plural': 'tables'},
        ),
    ]
