# Generated by Django 3.2.18 on 2023-04-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20230420_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last edit date'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last edit date'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last edit date'),
        ),
        migrations.AlterField(
            model_name='table',
            name='last_edit_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last edit date'),
        ),
    ]
