# Generated by Django 4.2.1 on 2023-06-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20230420_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entry', verbose_name='entry')),
                ('entry_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tablecolumn', verbose_name='entry field')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tablecolumn', verbose_name='target field')),
            ],
        ),
    ]
