version: '3.9'

services:

  paul:
    container_name: paul
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - "PYTHONUNBUFFERED=1"
    volumes:
      - ./api/paul_api/media:/var/www/paul_api/media
      - ./api/paul_api:/opt/paul_api/
    restart: on-failure
    ports:
      - ${PAUL_API_PORT:-8080}:80
    depends_on:
      - paul-db

  paul-db:
    hostname: paul-db
    image: postgres:12
    ports:
      - ${PAUL_DB_PORT:-5434}:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: on-failure


volumes:
  database-data:
    name: paul-pgdata
  media:
