# Generated by Django 3.1.2 on 2020-10-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0002_auto_20201006_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='audience_list_name',
            new_name='audience_table_name',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='audiences_members_list_name',
            new_name='audiences_members_table_name',
        ),
    ]
