# Generated by Django 3.1.2 on 2020-10-07 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_auto_20201006_0836'),
        ('plugin_mailchimp', '0008_auto_20201006_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_field', models.CharField(blank=True, max_length=100, null=True)),
                ('audience_id', models.CharField(blank=True, max_length=100, null=True)),
                ('segment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('filtered_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filter')),
            ],
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailchimp_tasks_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(choices=[('sync', 'Import tables'), ('segmentation', 'Send segmentation')], max_length=100)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('last_edit_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailchimp_tasks', to=settings.AUTH_USER_MODEL)),
                ('segmentation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plugin_mailchimp.segmentationtask')),
            ],
        ),
        migrations.AddField(
            model_name='taskresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='plugin_mailchimp.task'),
        ),
    ]
