# Generated by Django 3.1.2 on 2020-10-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0011_auto_20201007_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentationtask',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
