# Generated by Django 3.1.4 on 2020-12-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0021_auto_20201124_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_run_date',
            field=models.DateTimeField(null=True),
        ),
    ]
