# Generated by Django 3.2.18 on 2023-04-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0029_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='async_task_id',
            field=models.PositiveBigIntegerField(blank=True, default=0, editable=False),
        ),
    ]
