# Generated by Django 3.2.18 on 2023-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_mailchimp', '0030_task_async_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='async_task_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
