# Generated by Django 3.1.2 on 2020-11-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugin_woocommerce', '0006_auto_20201009_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='taskresult',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_woocommerce_taskresult_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
