# Generated by Django 3.1.3 on 2020-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin_woocommerce', '0009_task_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='table_abonamente',
            field=models.CharField(default='WC Abonamente', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='table_clienti',
            field=models.CharField(default='WC Clienti', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='table_comenzi_compact',
            field=models.CharField(default='WC Comenzi compact', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='table_comenzi_detaliat',
            field=models.CharField(default='WC Comenzi detaliat', max_length=255),
        ),
    ]
